# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Blog de Nicolas CHEYMOL
email: nicolas.cheymol@outlook.com
description: >-
  Bienvenue sur mon site personnel. Retrouvez mon portfolio, mon blog et mes projets.
baseurl: "" # le sous-répertoire de votre site, ex: /blog
url: "https://ncheymol.github.io" # l'URL de base de votre site
linkedin_username: ncheymol
github_username: ncheymol
author: Nicolas CHEYMOL
keywords: blog, projets, Intune, Cloud PC, CPC, Windows 365, Modern Management, ConfigMgr, PowerShell, Wakers

# SEO and Social Media
lang: fr
locale: fr_FR
timezone: Europe/Paris

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compress-images
  - jekyll-minifier

# Google Analytics
google_analytics:
  id: "G-GK9X2TK4W9"

# Performance optimizations
sass:
  style: compressed
  sourcemap: never

# Jekyll minifier settings for production
jekyll-minifier:
  exclude: ['*.json']
  uglifier_args:
    harmony: true
  compress_css: true
  compress_javascript: true
  remove_comments: true
  preserve_php: false
  remove_intertag_spaces: true
  remove_quotes: false
  compress_html: true

# Image optimization
compress_images:
  images_path: "**/*.{gif,png,jpg,jpeg,svg}"

# Feed settings
feed:
  posts_limit: 20
  excerpt_only: false

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections and defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nicolas CHEYMOL"
      show_excerpts: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Security settings
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Include/Exclude from processing
include:
  - _pages
  - .htaccess
  - robots.txt

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .git/
  - .gitignore

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
      start_line: 1
